# Generated by Django 5.2.17 on 2026-09-04 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0003_alter_product_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='color',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='color',
            field=models.ManyToManyField(related_name='OrderItem', to='products.color'),
        ),
    ]
