# Generated by Django 5.2.17 on 2026-09-04 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_orderitem_color_orderitem_color'),
        ('products', '0004_remove_product_color_product_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='color',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='color',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='OrderItem', to='products.color'),
            preserve_default=False,
        ),
    ]
